# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trans' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trans
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'trans-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'transTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'trans-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trans-tvOS

  target 'trans-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
